// Each level: a title, a one-line hint, and the grid itself.
// The edge of the grid is the edge of the world. Walls are only walls
// while some sentence says `stop=#` — and anything that touches the end
// of a sentence becomes part of it.
export const LEVELS = [
  {
    title: 'hello, world',
    hint: 'you are the @, because the board says you=@. walk into the $ to win. (arrows or wasd · z undo · r restart)',
    map: [
      '             ',
      '  @       $  ',
      '             ',
      'you=@   win=$',
    ],
  },
  {
    title: 'fill in the blank',
    hint: 'win= has nothing after it, so nothing wins. push a $ onto its end to finish the rule.',
    map: [
      '         ',
      ' win=  $ ',
      '         ',
      '  @    $ ',
      'you=@    ',
    ],
  },
  {
    title: 'one letter',
    hint: 'there is no win rule here, but the letters for one are lying around. spell it.',
    map: [
      '#########',
      '#       #',
      '#  i    #',
      '# w n=# #',
      '#   @   #',
      '#########',
      '         ',
      'you=@  stop=#',
    ],
  },
  {
    title: 'breakout',
    hint: 'the # walls are solid only because stop=# says so, and that sentence is part of the wall. break it.',
    map: [
      '#########         ',
      '#       #         ',
      '# @     #     $   ',
      '#       #         ',
      '# stop=##         ',
      '#       #         ',
      '#########         ',
      '                  ',
      ' you=@       win=$',
    ],
  },
  {
    title: 'glue',
    hint: 'anything pushed against the end of a sentence joins it. win=$ plus # is win=$#.',
    map: [
      '             ',
      '  win=  $ ## ',
      '         #  #',
      '   @     #  #',
      '          ## ',
      'you=@  stop=#',
    ],
  },
  {
    title: 'plural',
    hint: '',
    map: [
      '        #######',
      '  @     #  $  #',
      '        #  x  #',
      '        #######',
      ' you=@    x    ',
      '               ',
      'stop=#   win=$ ',
    ],
  },
  {
    title: 'the river',
    hint: '',
    map: [
      '         ~      ',
      '   @     ~   $  ',
      '         ~      ',
      ' you=@   ~      ',
      '         ~      ',
      'kill=~   ~ win=$',
    ],
  },
  {
    title: 'turncoat',
    hint: '',
    map: [
      '         ~      ',
      '   @     ~   $  ',
      '         ~   ~  ',
      '  win=   ~   ~~~',
      '         ~      ',
      'you=@   kill=~  ',
    ],
  },
  {
    title: 'paralysis',
    hint: 'solid things cannot move. not even you.',
    map: [
      '  #########  ',
      '  #   @ $ #  ',
      '  #########  ',
      '             ',
      '   x         ',
      '     stop=#@ ',
      '             ',
      ' you=@x      ',
      '       win=$ ',
    ],
  },
  {
    title: 'stand-in',
    hint: 'what becomes of a letter pushed out of its sentence?',
    map: [
      '             ',
      '  @          ',
      ' you=@       ',
      ' #### ###### ',
      ' #         # ',
      ' #      $  # ',
      ' ########### ',
      '             ',
      'stop=#  win=$',
    ],
  },
  {
    title: 'typo',
    hint: '',
    map: [
      '#########',
      '#       #',
      '#       #',
      '# wni =##',
      '#   @   #',
      '#########',
      '',
      'you=@ stop=#',
    ],
  },
  {
    title: 'martyr',
    hint: 'sometimes you have to become the word.',
    map: [
      '   #########   ',
      '   #       #   ',
      '   #   @   #   ',
      '   #       #   ',
      '   #########   ',
      '               ',
      '  @      win=  ',
      '               ',
      'you=@   stop=# ',
    ],
  },
  {
    title: 'spare body',
    hint: 'a broken sentence lets go of its letters.',
    map: [
      '          #######',
      '   @      #  $  #',
      '          #     #',
      ' you=@    #     #',
      '       you=@    #',
      '          #######',
      '                 ',
      ' stop=#   win=$  ',
    ],
  },
  // ---- book II: columns ----
  {
    title: 'crossword',
    book: 2,
    hint: 'while a row says read=v, every column is read top to bottom as well.',
    map: [
      '              ',
      '   w          ',
      '   i    @     ',
      '   n          ',
      '   =          ',
      '   $       $  ',
      '              ',
      'you=@  read=v ',
    ],
  },
  {
    title: 'standing up',
    book: 2,
    hint: 'a column needs its letters, same as a row.',
    map: [
      '                  ',
      '  w       ######  ',
      '  i   =   #    #  ',
      '  n       # $  #  ',
      '     @    #    #  ',
      '  #       ######  ',
      '                  ',
      'you=@ stop=# read=v',
    ],
  },
  {
    title: 'unread',
    book: 2,
    hint: 'reading is a law too.',
    map: [
      ' ######           ',
      ' #k   #   ~~~~~   ',
      ' #i   #   ~ $ ~   ',
      ' #l   #   ~   ~   ',
      ' #l   #   ~~~~~   ',
      ' #=   #           ',
      ' #~   #  @  read=v',
      ' #    #           ',
      ' ######  win=$    ',
      ' stop=#  you=@    ',
    ],
  },
  {
    title: 'the answer',
    book: 2,
    hint: 'one letter can belong to two sentences.',
    map: [
      '               ',
      '        w      ',
      '        i      ',
      '        n      ',
      '        =      ',
      ' you=@         ',
      '          @    ',
      '               ',
      '   read=v      ',
    ],
  },
  {
    title: 'reading glasses',
    book: 2,
    hint: '',
    map: [
      '    ##########  ',
      '    #   w    #  ',
      '    #   i  $ #  ',
      '    #   n    #  ',
      '    #   =    #  ',
      '    #   $    #  ',
      '    ##########  ',
      '                ',
      '  read=    v    ',
      '        @       ',
      ' you=@  stop=#  ',
    ],
  },
  {
    title: 'crossroads',
    book: 2,
    hint: 'a letter at a crossing serves two sentences. a sentence can travel whole.',
    map: [
      '   #k# ',
      '   #i# ',
      '   #l# ',
      '   #l# ',
      ' you=@ ',
      '   #~# ',
      '   ### ',
      '@      ',
      '~~~~~~~',
      '~  w  ~',
      '~  i  ~',
      '~  n $~',
      '~  =  ~',
      '~  $  ~',
      '~     ~',
      '~~~~~~~',
      'stop=# ',
      'read=v ',
    ],
  },
  {
    title: 'while nobody reads',
    book: 2,
    hint: '',
    solution: 'LLD URUU DDLLDDDR U LUURRUURR', // too deep for the solver to exhaust
    map: [
      ' ####          ',
      ' #k #    $     ',
      ' #i #~~~~~~~~~~',
      ' #l #   @      ',
      ' #l # read=v   ',
      ' #= #          ',
      ' #~ #   w      ',
      ' #  #   i      ',
      ' ####   n      ',
      '        =      ',
      'stop=#  $ you=@',
    ],
  },
  // ---- apocrypha: mined by miner.js, not designed ----
  {
    title: 'exchange',
    mined: true,
    hint: 'nobody designed this. a random search found it and the solver proved it.',
    map: [
      '  @  @ ',
      ' you=x@',
      '  win=$',
      '   =   ',
      '  #    ',
    ],
  },
  {
    title: 'understudy',
    mined: true,
    hint: 'nobody designed this. a random search found it and the solver proved it.',
    map: [
      '     @ ',
      '     = ',
      ' you=x@',
      '  win=x',
      '       ',
    ],
  },
  {
    title: 'the long way round',
    mined: true,
    hint: 'nobody designed this. a random search found it and the solver proved it.',
    map: [
      ' kill=~',
      '       ',
      'win=x  ',
      'you=@x ',
      '    @  ',
      ' =     ',
    ],
  },
];
