// Each level: a title, a one-line hint, and the grid itself.
// The edge of the grid is the edge of the world. Walls are only walls
// while some sentence says `stop=#` — and anything that touches the end
// of a sentence becomes part of it.
export const LEVELS = [
  {
    title: 'hello, world',
    hint: 'arrows or wasd to move · z undo · r restart',
    map: [
      '             ',
      '  @       $  ',
      '             ',
      'you=@   win=$',
    ],
  },
  {
    title: 'fill in the blank',
    hint: 'a rule is just text. text can be pushed.',
    map: [
      '         ',
      ' win=  $ ',
      '         ',
      '  @    $ ',
      'you=@    ',
    ],
  },
  {
    title: 'one letter',
    hint: 'words are made of letters. letters can be moved.',
    map: [
      '#########',
      '#       #',
      '#  i    #',
      '# w n=# #',
      '#   @   #',
      '#########',
      '         ',
      'you=@  stop=#',
    ],
  },
  {
    title: 'breakout',
    hint: 'walls are only walls because a sentence says so.',
    map: [
      '#########         ',
      '#       #         ',
      '# @     #     $   ',
      '#       #         ',
      '# stop=##         ',
      '#       #         ',
      '#########         ',
      '                  ',
      ' you=@       win=$',
    ],
  },
  {
    title: 'glue',
    hint: 'whatever touches the end of a sentence joins it.',
    map: [
      '             ',
      '  win=  $ ## ',
      '         #  #',
      '   @     #  #',
      '          ## ',
      'you=@  stop=#',
    ],
  },
  {
    title: 'plural',
    hint: '',
    map: [
      '        #######',
      '  @     #  $  #',
      '        #  x  #',
      '        #######',
      ' you=@    x    ',
      '               ',
      'stop=#   win=$ ',
    ],
  },
  {
    title: 'the river',
    hint: '',
    map: [
      '         ~      ',
      '   @     ~   $  ',
      '         ~      ',
      ' you=@   ~      ',
      '         ~      ',
      'kill=~   ~ win=$',
    ],
  },
  {
    title: 'turncoat',
    hint: '',
    map: [
      '         ~      ',
      '   @     ~   $  ',
      '         ~   ~  ',
      '  win=   ~   ~~~',
      '         ~      ',
      'you=@   kill=~  ',
    ],
  },
  {
    title: 'paralysis',
    hint: 'solid things cannot move. not even you.',
    map: [
      '  #########  ',
      '  #   @ $ #  ',
      '  #########  ',
      '             ',
      '   x         ',
      '     stop=#@ ',
      '             ',
      ' you=@x      ',
      '       win=$ ',
    ],
  },
  {
    title: 'typo',
    hint: '',
    map: [
      '#########',
      '#       #',
      '#       #',
      '# wni =##',
      '#   @   #',
      '#########',
      '',
      'you=@ stop=#',
    ],
  },
  {
    title: 'martyr',
    hint: 'sometimes you have to become the word.',
    map: [
      '   #########   ',
      '   #       #   ',
      '   #   @   #   ',
      '   #       #   ',
      '   #########   ',
      '               ',
      '  @      win=  ',
      '               ',
      'you=@   stop=# ',
    ],
  },
  {
    title: 'spare body',
    hint: 'a broken sentence lets go of its letters.',
    map: [
      '          #######',
      '   @      #  $  #',
      '          #     #',
      ' you=@    #     #',
      '       you=@    #',
      '          #######',
      '                 ',
      ' stop=#   win=$  ',
    ],
  },
];
