export const LEVELS = [
  { title: 'crossword', map: [
    '              ',
    '   w          ',
    '   i    @     ',
    '   n          ',
    '   =          ',
    '   $       $  ',
    '              ',
    'you=@  read=v ',
  ]},
  { title: 'standing up', map: [
    '                  ',
    '  w       ######  ',
    '  i   =   #    #  ',
    '  n       # $  #  ',
    '     @    #    #  ',
    '  #       ######  ',
    '                  ',
    'you=@ stop=# read=v',
  ]},
  { title: 'unread', map: [
    ' ######           ',
    ' #k   #   ~~~~~   ',
    ' #i   #   ~ $ ~   ',
    ' #l   #   ~   ~   ',
    ' #l   #   ~~~~~   ',
    ' #=   #           ',
    ' #~   #  @  read=v',
    ' #    #           ',
    ' ######  win=$    ',
    ' stop=#  you=@    ',
  ]},
  { title: 'the answer', map: [
    '               ',
    '        w      ',
    '        i      ',
    '        n      ',
    '        =      ',
    ' you=@         ',
    '          @    ',
    '               ',
    '   read=v      ',
  ]},
  { title: 'reading glasses', map: [
    '    ##########  ',
    '    #   w    #  ',
    '    #   i  $ #  ',
    '    #   n    #  ',
    '    #   =    #  ',
    '    #   $    #  ',
    '    ##########  ',
    '                ',
    '  read=    v    ',
    '        @       ',
    ' you=@  stop=#  ',
  ]},
];
