export const LEVELS = [
  { title: 'stand-in', map: [
    '             ',
    '  @          ',
    ' you=@       ',
    ' #### ###### ',
    ' #         # ',
    ' #      $  # ',
    ' ########### ',
    '             ',
    'stop=#  win=$',
  ]},
  { title: 'stand-in b', map: [
    '               ',
    '  @            ',
    '               ',
    '  #####@####   ',
    '  #        #   ',
    '  #  $     #   ',
    '  ##########   ',
    '               ',
    ' stop=#  win=$ ',
    '    you=@      ',
  ]},
];
