export const LEVELS = [
  { title: 'crossroads', map: [
    '   #k# ',
    '   #i# ',
    '   #l# ',
    '   #l# ',
    ' you=@ ',
    '   #~# ',
    '   ### ',
    '@      ',
    '~~~~~~~',
    '~  w  ~',
    '~  i  ~',
    '~  n $~',
    '~  =  ~',
    '~  $  ~',
    '~     ~',
    '~~~~~~~',
    'stop=# ',
    'read=v ',
  ]},
];
